export const GET_THEMES_BEGIN = 'GET_THEMES_BEGIN';
export const GET_THEMES_SUCCESS = 'GET_THEMES_SUCCESS';
export const GET_THEMES_ERROR = 'GET_THEMES_ERROR';
export const LOAD_THEMES = 'LOAD_TEMPLATES';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
